name = "image-background-remover"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "image-bg-users"
database_id = "b269fc49-5023-43f9-9818-e4faca4908c4"
